Update terraform-destroy.yml

diff --git a/.github/workflows/terraform-destroy.yml b/.github/workflows/terraform-destroy.yml
--- a/.github/workflows/terraform-destroy.yml
+++ b/.github/workflows/terraform-destroy.yml
@@ -49,13 +49,13 @@ jobs:
         uses: actions/checkout@v4
 
       # Verificação manual de confirmação
-      - name: Confirm Destruction
-        if: github.event_name == 'workflow_dispatch'
-        run: |
-          if [ "${{ inputs.confirm-destroy }}" != "confirm" ]; then
-            echo "::error::Destruction not confirmed. You must type 'confirm' to proceed."
-            exit 1
-          fi
+      # - name: Confirm Destruction
+      #   if: github.event_name == 'workflow_dispatch'
+      #   run: |
+      #     if [ "${{ inputs.confirm-destroy }}" != "confirm" ]; then
+      #       echo "::error::Destruction not confirmed. You must type 'confirm' to proceed."
+      #       exit 1
+      #     fi
 
       - name: Configure AWS Credentials
         uses: aws-actions/configure-aws-credentials@v4
